/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CampaignService } from "../campaign.service";
import { CampaignCreateInput } from "./CampaignCreateInput";
import { Campaign } from "./Campaign";
import { CampaignFindManyArgs } from "./CampaignFindManyArgs";
import { CampaignWhereUniqueInput } from "./CampaignWhereUniqueInput";
import { CampaignUpdateInput } from "./CampaignUpdateInput";
import { CampaignReportFindManyArgs } from "../../campaignReport/base/CampaignReportFindManyArgs";
import { CampaignReport } from "../../campaignReport/base/CampaignReport";
import { CampaignReportWhereUniqueInput } from "../../campaignReport/base/CampaignReportWhereUniqueInput";

export class CampaignControllerBase {
  constructor(protected readonly service: CampaignService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Campaign })
  async createCampaign(
    @common.Body() data: CampaignCreateInput
  ): Promise<Campaign> {
    return await this.service.createCampaign({
      data: data,
      select: {
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Campaign] })
  @ApiNestedQuery(CampaignFindManyArgs)
  async campaigns(@common.Req() request: Request): Promise<Campaign[]> {
    const args = plainToClass(CampaignFindManyArgs, request.query);
    return this.service.campaigns({
      ...args,
      select: {
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Campaign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async campaign(
    @common.Param() params: CampaignWhereUniqueInput
  ): Promise<Campaign | null> {
    const result = await this.service.campaign({
      where: params,
      select: {
        createdAt: true,
        description: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Campaign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCampaign(
    @common.Param() params: CampaignWhereUniqueInput,
    @common.Body() data: CampaignUpdateInput
  ): Promise<Campaign | null> {
    try {
      return await this.service.updateCampaign({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          name: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Campaign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCampaign(
    @common.Param() params: CampaignWhereUniqueInput
  ): Promise<Campaign | null> {
    try {
      return await this.service.deleteCampaign({
        where: params,
        select: {
          createdAt: true,
          description: true,
          endDate: true,
          id: true,
          name: true,
          startDate: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/campaignReports")
  @ApiNestedQuery(CampaignReportFindManyArgs)
  async findCampaignReports(
    @common.Req() request: Request,
    @common.Param() params: CampaignWhereUniqueInput
  ): Promise<CampaignReport[]> {
    const query = plainToClass(CampaignReportFindManyArgs, request.query);
    const results = await this.service.findCampaignReports(params.id, {
      ...query,
      select: {
        bounceCount: true,

        campaign: {
          select: {
            id: true,
          },
        },

        clickCount: true,
        createdAt: true,
        id: true,
        openCount: true,
        sentCount: true,
        spamCount: true,
        unsubscribedCount: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/campaignReports")
  async connectCampaignReports(
    @common.Param() params: CampaignWhereUniqueInput,
    @common.Body() body: CampaignReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      campaignReports: {
        connect: body,
      },
    };
    await this.service.updateCampaign({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/campaignReports")
  async updateCampaignReports(
    @common.Param() params: CampaignWhereUniqueInput,
    @common.Body() body: CampaignReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      campaignReports: {
        set: body,
      },
    };
    await this.service.updateCampaign({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/campaignReports")
  async disconnectCampaignReports(
    @common.Param() params: CampaignWhereUniqueInput,
    @common.Body() body: CampaignReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      campaignReports: {
        disconnect: body,
      },
    };
    await this.service.updateCampaign({
      where: params,
      data,
      select: { id: true },
    });
  }
}
